### ISSUE TITLE
Update data loader to match new Measuring Point data

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#122]
# From `data\Reference_Points.csv` commit `231036c` notes:

>To obtain correct list of MP and their elevations, use the new Reference_Points.csv and use the following information to remove unwanted data
>
>IF column "ReferencePointPeriods_0_IsMeasuredAgainstLocalAssumedDatum" is set to "TRUE" discard all MP that start with "Ref point is"
>
>IF column ""ReferencePointPeriods_0_IsMeasuredAgainstLocalAssumedDatum" is set to "FALSE" discard MP's with the following names: "Land Surface Datum",  "NAVD88 0ft", "NGVD29 0ft" "Slab"
>
>DisplayOrder has been added

# Additional logic

From 2023-08-17 meeting with @kprice-TLH and @craignwf 

Note that `Monitoring_Type` values referenced below are fetched from `District Monitoring.xlsx`.

## Data Logger

- If `Monitoring_Type` is 'Rainfall' or 'Vel.Ind':
  - Must have Data Logger, meaning reject Location if:
    - No Data Logger found in `District Monitoring.xlsx`
    - Data Logger was rejected as invalid

## Measuring Point

- If `Monitoring_Type` is 'GW level' or 'Stage':
  - Must have at least one valid Measuring Point, meaning reject Location if:
    - No Measuring Points found in `Reference_Points.csv`
    - All Measuring Points found were rejected as invalid

## Sensor

`District Monitoring.xlsx` stores tipping buckets and other sensors in separate columns. The hydro geodatabase model stores all Sensors together. Keep this in mind when implementing the logic below:

- If `Monitoring_Type` is 'Rainfall':
  - Must have at least one tipping bucket, meaning reject Location if:
    - No tipping bucket found in `District_Monitoring.xlsx`
    - Tipping bucket was rejected as invalid

# Tasks

- [x] @mmannion Update data loader
- [x] @mmannion Reload updated data to production database
- [x] @mripp Export updated Measuring Points to CSV for Survey
- [x] @kprice-TLH Review existing geodatabase to verify that things are as expected (given latest available data/logic)
  - Close this if so

**Comment by kprice-TLH** [comment]
[RP_MP_comparison_KP.xlsx](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/files/12409150/RP_MP_comparison_KP.xlsx)

Using the RP_MP_comparison, I found that 8 locations were missing from the DM spreadsheet. I added them and uploaded a new copy of the DM sheet. 

Locations 12966, 12967,12968,12969, &12970 were not processed at all. Perhaps they were not on the last DM spreadsheet.

18 locations were not processed because they had no sensor/ SN. The new logic should fix this. They have dataloggers but no additional sensor.
