### ISSUE TITLE
Add `HasSensor/MeasuringPoint` columns

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#126]
# Business Case
The survey needs to know, for each Location, whether the Location has any Sensors or Measuring Points so it can show/hide the relevant sections. Various columns on the `Location` table prefixed with `Has` indicate similar properties; we need to add equivalent columns for Sensors and Measuring Points.

# Semantics

## `Has` vs. Relationship

The `Location.Has*` columns indicate whether a Location _should_ have certain equipment (e.g. `HasDataLogger`) or activities (`HasWaterQuality`) associated with it.

Relationships between the `Location` table and the asset management tables - `DataLogger`, `Sensor`, and `MeasuringPoint` - allow discovering which equipment is currently known to be associated with a Location.

Real-world conditions can differ from the intent for a Location. For example, a Location may need a Data Logger, and have had one installed previously, but the logger could be found to have been stolen during a visit. Therefore, the database could correctly reflect `Location.HasDataLogger` as 'Yes', but have no relationship to a corresponding row in the `DataLogger` table. (Note that a back-office analyst would need to make this update, because the survey is designed to disallow editing asset data.)

Accordingly, the survey shows/hides sections based on the intended properties of a Location (`Has` columns) independently of whether related asset records exist.

See the [wiki](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/wiki/Data-Model#intended-and-actual-assets) for more information.

## `HasSensor`

Some equipment includes a Sensor and integrated Data Logger as a single physical unit. Locations with such equipment will be configured in the database as:

- `HasDataLogger` = 'Yes'
- `HasSensor` = 'No'

In cases where the Data Logger and Sensor are separate units, the database will reflect:

- `HasDataLogger` = 'Yes'
- `HasSensor` = 'Yes'

# Populating Values

Populate the new `HasSensor` and `HasMeasuringPoint` columns based on the presence or absence of these items in the source data:

- `HasSensor`: In `District Monitoring.xlsx`, presence or absence of values in `Type of Sensor` / `Sensor Serial #` columns for each Location (row)
  - Note that tipping buckets are also Sensors, but their data determines the `HasRainfall` value, not `HasSensor`

-  `HasMeasuringPoint`: In `Reference Points.csv`, presence or absence of at least one row for each Location (per `Identifier` column)

# Tasks

- [x] @mmannion Add two columns to `Location` table:
  - `HasSensor`
  - `HasMeasuringPoint`

- [x] @mmannion Update data loader to populate new columns

- [x] @mripp ADD SURVEY TASK(S) HERE

**Comment by mmannion** [comment]
- Added `Location` columns:
  - `HasSensor`
  - `HasMeasuringPoint`
- Updated data loader to populate new columns
- Updated data model diagram
- Deployed changes production database

**Comment by mripp** [comment]
Added columns to survey see #123
