### ISSUE TITLE
Misc. Changes to Survey

### ISSUE THREAD

**Issue by SarahNWF** [NWFWMD-IT/Hydrologic-Monitoring-Project#200]
1. Reword the question in Specific Conductance from "Was the sensor calibrated?" to "Will the sensor be calibrated?"
2. Change "Data Logger Time Adjustment (minutes)" to "Data Logger Time Difference (minutes)" and "Data Logger Time Adjustment (minutes; new battery) to Data Logger Time Difference (minutes; new battery)
3. Move "Data Logger Time Difference (minutes) before "Data Logger Time Adjusted" in visit summary
4. Make sure the voltage recording is showing up by default
5. Add another domain to the Issue Type called "General Note", be below "Other" so staff can record comments about a station that aren't really "problems"

# Tasks

- [x] @mmannion For item 5, update domain _Location Issue Type_ to include value "General Note"
- [x] @mmannion Manually update data model in `sql-gis`
- [x] @SarahNWF Implement all issues above in XLSForm
- [x] @SarahNWF Publish updated survey

**Comment by mmannion** [comment]
- Committed domain update (item 5) to branch `DistrictMonitoring2Aquarius`
- Manually applied change to `hydro` database on `sql-gis`

@kprice-TLH @craignwf Does adding the 'General Note' value to the _Location Issue Type_ domain require any changes in the geodatabase > Aquarius importer?

I ask for two reasons:
- Craig, it may be case that the importer code needs to know the domain values to tag things properly. FYI, if so.
- Katie, I understand that 'General Note' is different than the other values because it's not a "problem" per se. Therefore, if it needs to be handled specially on import, please let Craig know.
