### ISSUE TITLE
Rename LocationVisit.BatteryVoltage columns to BatteryLevel

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#201]
Change `LocationVisit` column names to reflect multiple battery level units (i.e. volts, percent, mAh):
- `BatteryVoltage` > `BatteryLevel`
- `BatteryVoltage2` > `BatteryLevel2`

# Tasks

- [x] @mmannion Update data model deployment script
- [x] @mmannion Manually deploy column name changes to `sql-gis`
- [x] @SarahNWF Update Survey to reference new column names
- [x] @SarahNWF Publish updated Survey
- [ ] @craignwf Update Aquarius importer to use new column names

**Comment by mmannion** [comment]
- Committed update to `DistrictMonitoring2Aquarius`
- Manually applied changes to `hydro` geodatabase on `sql-gis`
