### ISSUE TITLE
Compile photo source data

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#81]
Notes from Teams chat:

- Craig gave us a tour of some photos in Aquarius and described how they are stored
  - Most Locations don't have photos
  - Locations that do have photos may have a bunch
    - Not all will be relevant for Survey123
    - There is not reliable metadata we can use to automatically determine which should be attached to a Location and which should be attached to a MeasuringPoint in our model

# Tasks

- [x] @craignwf Develop an approach for compiling the photos we want to view in Survey123 and tagging them so that we can load them to the right place
- [x] @kprice-TLH Send email to field staff with instructions for collecting photos
- [ ] @Bikechain Review tasking with staff at quarterly meeting
- [x] @kprice-TLH Load photos to Aquarius and associate with proper Location / Measuring Point

**Comment by mmannion** [comment]
@Bikechain to collect photos for Locations to be tested, of:
- Location overview
- Measuring Point(s)

**Comment by mmannion** [comment]
Pending email to field staff > discussion at quarterly meeting
